### ISSUE TITLE
Release `1.60.2`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/vscode-native-svg-preview#11]
## `1.60.2`

- [x] Cross-channel testing for `1.60.2` (VSC, Insiders, GitHub Codespaces, VSCodium).
- [x] Update asset references.
- [x] Create tag release for GitHub.
- [ ] Publish `1.60.2` to Visual Studio Marketplace.
- [ ] Publish `1.60.2` to OpenVSIX.

## Changelog

Move preview screenshot from `editor-overview.png` to `editor-preview.png` in repository.
