### ISSUE TITLE
Publish 1.67.1

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/vscode-native-svg-preview#13]
## `1.67.1`

- [x] Cross-channel testing for `1.67.1` (VSC, Insiders, GitHub Codespaces, VSCodium).
- [x] Update asset references.
- [x] Create tag release for GitHub.
- [x] Publish `1.67.1` to Visual Studio Marketplace.
- [x] Publish `1.67.1` to OpenVSIX.

## Changelog

- Fix zooming out on images on Mac devices (microsoft/vscode#131080)
- Fix image background checkerboard after scaling (microsoft/vscode#141292)
