### ISSUE TITLE
Publish `1.60.0`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/vscode-native-svg-preview#3]
## `1.60.0`

- [x] Cross-channel testing for `1.60.0` (VSC, Insiders, GitHub Codespaces, VSCodium).
- [x] Update asset references.
- [x] Create tag release for GitHub.
- [x] Publish `1.60.0` to Visual Studio Marketplace.
- [x] Publish `1.60.0` to OpenVSIX.

## Changelog

- Support for SVGs that are renderable in the Chromium browser.
- Adaptive checkerboard background matching the native image preview.
- Reflow mode for SVG documents without a bounding box (`viewBox`).
- Editor preview screenshot to the documentation for end users.
