### ISSUE TITLE
Publish `1.60.1`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/vscode-native-svg-preview#7]
## `#.#.#`

- [x] Cross-channel testing for `1.60.1` (VSC, Insiders, GitHub Codespaces, VSCodium).
- [x] Update asset references.
- [x] Create tag release for GitHub.
- [x] Publish `1.60.1` to Visual Studio Marketplace.
- [x] Publish `1.60.1` to OpenVSIX.

## Changelog

- Disable preview actions in side-by-side diff view.
- Fix for broken 404 editor preview screenshot.
